### ISSUE TITLE
"Metadata incomplete" is not specific enough

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#43] opened 2022-01-27 19:50 UTC
This user case with Andre Pun (UW) tells us that simply saying "metadata incomplete" is not good enough. 

Should we think about spelling out a list of the fields that need to be addressed in order to make the metadata complete to the users, and by clicking on each of them, they can be taken to those specific fields?

**Comment by lkamb** [comment] 2022-01-27 20:04
Duplicate of #41

**Closed by lkamb** 2022-01-27 20:04 UTC
